/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
 * the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>
#include <stdlib.h>

int main() {

	int fiboA = 0, fiboB = 1, fiboC, sum = 0;

	for (fiboC = 1; fiboC <= 4000000; fiboC = fiboA + fiboB) {
		fiboC = fiboA + fiboB;
		fiboA = fiboB;
		fiboB = fiboC;

		if (fiboC % 2 == 0) {
			sum += fiboC;
		}
	}

	printf("ANSWER = %d\n", sum);

	return 0;
}